language: python
sudo: required
python:
- '2.7'
- '3.6'
install:
- pip install pytest-cov codeclimate-test-reporter
- pip install .
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
script:
- "./cc-test-reporter before-build"
- py.test -s --cov=opencellid --cov-report xml tests/
- "./cc-test-reporter after-build"
deploy:
  provider: pypi
  repo: ashmastaflash/opencellid-wrapper
  user: ashmastaflash
  on:
    tags: true
  password:
    secure: EaZpOq91wBqFxnx6Rf1jYtZgqQkVlJitNVOLTEmhYxrhM19A+4++ifcb77QMSXysClhaA9bUDwOyzrzD7c5pqtMnX8yEMq6P9OH/0x7EWqjfU5iXgIy4X9KvUxmbb+Y119V7okR0Q6uH2wvmEnDqLYfwrHWSNZiOg+4cIskkdU1RIYL6rc2EiLDsTuvB6Qmyv0fqjeOaWmj1zhYsC6rR8IiFnN/7UOX6rcFU7m56OWV/EkQ35XGN/uvgSwSOtmtnNV7qQwiG5nwflOXagM2WIR2VupocXar5ZF5PVBKKgVFsPswblXch4AsOoPS9HSDkJzHOEB4HW0YaCMbcbhhmiCWu/7fA91t/Z+Ovn/1he6GC/UW4dMFuoAV7Ka/k7AiRIG8qfCMIR1/mV4koe29KNhsUpyBVSD/9o8SZIr/02zytCCULPjXbv1065vt+D6lqOyKed0/r1Sj0r4yd2DDTaZBGra2jyBeWNFKn3lN3KNqYGgCcoB6xFq7zLMXX5FJU+17/QAOnGWzzdVes/BnN28LYt1sQXPeHyduxzRUf9CMUU1RgHUsNKJvW7W3vN/znVqdoLjRWR2iVUb4i2khYzCeJa3SVXwq81RdKmtO5NgFufdyqHf/O1rHAZN6JTI9TuizRe9COsXq/n4algEubc0GD8lOjARhiZJnShTB9biw=
env:
  global:
  - secure: P5lUiC8M/7A7V4bsUsnCt9F0Jz5x72bpOnshlP2OnaRCtYVeq4aGsv1WdOmtkSvNAVDnTPEof158nqLnNVJGDYVA/kyKfqGmJ45uR3TkcQC8jbmZ/VdRoVYho6j2l4JUeTUOUhbqWothJtkdq1uU32cpRevXm3ZqdMh9tXOMHplU0Fd6f/8N8w16E0pM62q04dpw5/xt7K+TPwpm93o8FQCihi3qWYQ7aVb5Er1ja3ZqMGPNbM3QODnKehz0+HhtgF6V5S1nB+tTOUI/t3ih5d/rf7s6hvjRsDFuFdRlqwgCBIedOldB0o1m+xjQF8nVY2PugU1ee7J1zYGGGmXfobl9ZiPK5hMzAuzAWx3nrYIe+i3iqWWvQhORwLnuqBPv6Vf5CmXFo3gtuWNFlkTURH7uZJ7+zyqWhRu51Sgg61e7j5kcLojkW1bNGZgMZBlseD+JjH1xm/a9ii3a3JQC8kVOECm+M+geytLG4i36NAQNjqqi0KKlrzJwmKeSRA8w2zP1OEEjEPZh5o7wfnqRo10q7/i57sCpN+YXZE/84Ea0029f6fRkVhrfG/pGjcVQzgcppG3eLNImIxX4Qh9+Keyy6belRvp4b0+YibMoLxuPP+aVDlNrhf5+P6vN0kbiyXineWLDpaSYenuYBek0YLrexmv23cR2xlcJwqbsuy4=
  - secure: rN+nAK0dgRIcxgDMuFUEEv40ccjnO2/Er+fXORgoyGXxTpNAVgd4pyXAy7bMTEl56t0RPBhXAY2owgmUuy6aVREdK19sTDXZyumrgvtRYwJZst/MIxsC3pZCvzdPB8wfOemYK2WuKK7P/lT97EqG5iy4q9CxOrQe7kWbGYd4Ol8DGCYZhvYJRG5o9moaFuigKGC/l+FJJc4NUks17p2UdFOrsCnHBHzI65G4Qxf8HXpczaBnbb1oRQde/EvH6WZgbYKgEwc+Mq3HCCPda/WCir+pTx/YBgZzNRV11gsOnbmBnUvSwF1KhtOXi9MLqUh0aaTTecsH24iT1PRybJ+i020uk/+NpDbFT4flLol9JcN7nErL56EP02jpU11F/8xnSSYtVVrQnydhXtPrvRTuolZ10UZUpD2P3raJyDYuMNZ06XAiJ7cDYBKxzIVkGPYnHUFffkyW/C+IwvWVNy8z9sAXjClSREndjxlw5aZGUuLAWpfsZBUeogZa93FGx93pCpriAE/yg8xe1/PFRYUUPk1NybC/xtUhmZVqyZLBuZhXDgBtEqz8lK7aY/mt9QmYDYRrD3FbjGSfnUkA4CLBTcCP0wzC/FNt9GVu1y9o4Bn+XbSbHArAAVedjYgIpbf6RMQ4ceOys7yYpLh7Fue9PiZb80RBSogKTWorHZrTXug=
