language: python
sudo: required
python:
- '2.7'
install:
- pip install pytest-cov codeclimate-test-reporter
- pip install .
script: py.test -s --cov=opencellid tests/
after_success:
- echo "Need to fix code coverage reporting!"
env:
  global:
    secure: P5lUiC8M/7A7V4bsUsnCt9F0Jz5x72bpOnshlP2OnaRCtYVeq4aGsv1WdOmtkSvNAVDnTPEof158nqLnNVJGDYVA/kyKfqGmJ45uR3TkcQC8jbmZ/VdRoVYho6j2l4JUeTUOUhbqWothJtkdq1uU32cpRevXm3ZqdMh9tXOMHplU0Fd6f/8N8w16E0pM62q04dpw5/xt7K+TPwpm93o8FQCihi3qWYQ7aVb5Er1ja3ZqMGPNbM3QODnKehz0+HhtgF6V5S1nB+tTOUI/t3ih5d/rf7s6hvjRsDFuFdRlqwgCBIedOldB0o1m+xjQF8nVY2PugU1ee7J1zYGGGmXfobl9ZiPK5hMzAuzAWx3nrYIe+i3iqWWvQhORwLnuqBPv6Vf5CmXFo3gtuWNFlkTURH7uZJ7+zyqWhRu51Sgg61e7j5kcLojkW1bNGZgMZBlseD+JjH1xm/a9ii3a3JQC8kVOECm+M+geytLG4i36NAQNjqqi0KKlrzJwmKeSRA8w2zP1OEEjEPZh5o7wfnqRo10q7/i57sCpN+YXZE/84Ea0029f6fRkVhrfG/pGjcVQzgcppG3eLNImIxX4Qh9+Keyy6belRvp4b0+YibMoLxuPP+aVDlNrhf5+P6vN0kbiyXineWLDpaSYenuYBek0YLrexmv23cR2xlcJwqbsuy4=
