language: python
sudo: required
python:
- '2.7'
install:
- pip install pytest-cov codeclimate-test-reporter 
- pip install .
script: py.test -s --cov=opencellid tests/
after_success:
- codeclimate-test-reporter --token ${CODECLIMATE_REPO_TOKEN}
env:
  global:
  - secure: bFP0qIs1SY99qTo1R/Iu8crrgwikNvhq4lCeDkNbFwYIa8PElVmxvoxRXssA3IS/Qf4QaHE5M61yCtzAZsW6IMD99RGLSxHr2URIVuF2YF9jQI5297I1ONtJ+HjqTEf/YeK9LtrEblX58N6tnqpFfH9TaluKb26FGHBC+GGCFS95KA3h3J1fvxixjaNgMJXYmzl/DZXF/cFuSQyHdU8iZ3j9OOaZaLhHeTgfPZixgXW+6/GfR/uJ/nGXsFUiBMyElf+zunOfJRRiozftOpkrM70Q5vBYgMqOoMCy0xPko0QWY3niOLzgYTf7qjrt8hljxaY7rNkMX0HO/v9ImkfM+7crW5OFP5PeaREjLDWMmNP9af/TW7iMRhyOQS2rOARRzbLQYWVd2qmgkFRwrNu0CuH28aROQG8TZzOM213WBLN4UBYZVpDadkNTAcA+eTutmZoRwUyEAoFYYinRaUJuuDJQhUqgsB2OWFF/1jOvkCvA6CKnP1tNKWpHq9yDJ9Pjce76LLDYo2otCUc/f1LyBZSMrKpDWjJR0buzx2sAXHS49C98bYjgrVhu7zKSEMI6SLKlS8kTJBv8xWb1SvBl8WSX8DVYNJ5U6yIJAa5fsUNbHeMcaWP3kaMUQD4aMhsirOKhwN/2ObYeLZIWfjE//QvgK4PRPkbrLQdhpTCv88g=
  - secure: Tj6BkBzhLwMLfIAWkwZGuWf2DK5dw4U8rfwVuMjm+prdjhOhc6NSkhSNWoWByLLpR3Xew4yb8b1SAXy7/FkpCwRMyViAcHpVDxeNKb2N81uii4xHDV+ClzYT4FYIoEK6DGyo7ybC05dF6Kh6PeE6DLeKz4b3CDeobzUXHmJGnMTYCG71F3sboQCduhjgAMOqXu4xK7LA51l8Knv9nfVLifVtIczbZnHLrbtiz8BW5BQbY16ahR1ed0WpplEzheov5zja2YLCBntBV2hRFqRuts6rSTek4laX6x5PyASHkVTdLxtDjsyxQeeqjlVGYUDMGuC8aVGi73YcHkW/Rnu6ruwgmFW4vYtz2o5tVzSQ/EMKiB2ZfOCJaRgsWbQQ9oXVKbc5fiyPT8eOu+oubhcop7PbyLcbPB1EmcwTEvFdChzyX55u9943xnfIG6MZQiwsrPZsCVTd/hyewy09MsidKbOnnUo9hNgusDs6VPRlnPIcsCAY5oKajo29RiW+O0xvPBm/GsqXESJgxrKvOlHB9kWqNGii/kqaL2QubfGgZsucZS0KVajFi+P2JWasTYzPjnjmhYFi8iwKoYQYOiRS4RH+1Qy8dMm2H1vuGxnOsQ9ttyO1nh1uAIHsySFulBWd6yg+aUI3dOUq31zca5mpfWa5yMOUVN3oCmxscOHxDQk=
